# Generated by Django 5.0.4 on 2024-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_blacklist_customer_blacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientServicePackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255)),
                ("max_groups_count", models.IntegerField(default=0)),
                ("max_keywords_count", models.IntegerField(default=0)),
                ("max_comments_per_month", models.IntegerField(default=0)),
                ("max_facebook_profile_count", models.IntegerField(default=0)),
                ("use_ai", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
