# Generated by Django 5.0.4 on 2024-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_group_category_alter_keyword_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Group Name"),
        ),
        migrations.AlterField(
            model_name="group",
            name="url",
            field=models.URLField(unique=True, verbose_name="Group URL"),
        ),
    ]
