# Generated by Django 5.0.4 on 2024-04-29 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_clientservicepackage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientservicepackage",
            name="max_comments_per_month",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="clientservicepackage",
            name="max_facebook_profile_count",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="clientservicepackage",
            name="max_groups_count",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="clientservicepackage",
            name="max_keywords_count",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
