# Generated by Django 5.0.4 on 2024-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_group_name_alter_group_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Category Name"),
        ),
    ]
