# Generated by Django 5.0.6 on 2024-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_max_pack"),
        ("posts", "0002_rename_post_url_post_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="matched_posts",
            field=models.ManyToManyField(blank=True, related_name="matched_posts", to="posts.post"),
        ),
    ]
