# Generated by Django 5.0.4 on 2024-04-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_clientservicepackage_max_comments_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="service_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.clientservicepackage",
            ),
        ),
    ]
