# Generated by Django 5.0.4 on 2024-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="groups_keywords",
            field=models.ManyToManyField(blank=True, related_name="groups_keywords", to="customers.keyword"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="keywords",
            field=models.ManyToManyField(blank=True, related_name="keywords", to="customers.keyword"),
        ),
        migrations.DeleteModel(
            name="GroupKeyword",
        ),
    ]
