# Generated by Django 5.0.4 on 2024-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_service_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.TextField(verbose_name="Keyword name"),
        ),
    ]
