# Generated by Django 5.0.6 on 2024-06-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_matched_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
