# Generated by Django 5.0.6 on 2024-06-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("customers", "0006_customer_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="groups_keywords",
        ),
        migrations.AlterField(
            model_name="customer",
            name="keywords",
            field=models.ManyToManyField(blank=True, related_name="groups_keywords", to="common.keyword"),
        ),
    ]
