# Generated by Django 5.0.6 on 2024-06-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("customers", "0007_remove_customer_groups_keywords_and_more"),
        ("posts", "0006_remove_post_slug_remove_post_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="matched_posts",
        ),
        migrations.CreateModel(
            name="CustomerPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("keywords", models.ManyToManyField(blank=True, related_name="posts_keywords", to="common.keyword")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="matched_users", to="posts.post"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
