version: '3.9'

services:
  common:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:1.22.0
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles/:/var/www/app/static/:ro
      - ./media/:/var/www/app/media/:ro

  web:
    extends:
      service: common
    command: poetry run python manage.py runserver 0.0.0.0:8080
    ports:
      - '8080:8080'

  bot:
    extends:
      service: common
    command: poetry run python manage.py bot

  celery:
    extends:
      service: common
    command: poetry run python -m celery -A config worker -l INFO
    depends_on:
      - redis

  celery-beat:
    extends:
      service: common
    command: poetry run python -m celery -A config beat -l INFO
    depends_on:
      - redis

  redis:
    image: redis:6
    restart: on-failure
