version: '3.9'

services:
  common:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    extra_hosts:
        - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.22.0
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles/:/var/www/app/static/:ro
      - ./media/:/var/www/app/media/:ro

  web:
    extends:
      service: common
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    command: ./start

  celery:
    extends:
      service: common
    command: poetry run celery -A config worker -l INFO
    depends_on:
      - redis

  redis:
    image: redis:6
    restart: on-failure
