# Generated by Django 5.0.6 on 2024-06-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Group Name"),
            preserve_default=False,
        ),
    ]
