# Generated by Django 5.0.6 on 2024-06-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_blacklist_unique_black_list_name_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="customer",
        ),
    ]
