# Generated by Django 5.0.6 on 2024-06-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_category_name_alter_group_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="name",
        ),
    ]
