# Generated by Django 5.0.6 on 2024-06-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_category_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicBlackList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Public Keyword Name")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("url", models.URLField(verbose_name="Group URL")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Public Keyword Name")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
