# Generated by Django 5.0.6 on 2024-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="original_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
