# Generated by Django 5.0.6 on 2024-06-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_post_url_post_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="group_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="group_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
