# Generated by Django 5.0.6 on 2024-06-12 03:11

import apps.posts.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_group_link_post_group_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="original_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.utils.upload.get_post_image_path),
        ),
    ]
