# Generated by Django 5.0.6 on 2024-06-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_postimage_original_image_url_alter_postimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
