# Generated by Django 5.0.4 on 2024-04-19 01:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("photo_url", models.URLField(unique=True, verbose_name="Photo URL")),
                (
                    "photo_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Photo ID"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
